### ISSUE TITLE
Does not handle events flowing over months

### ISSUE THREAD

**Issue by Rotund** [wreckage/django-happenings#1]
I had an event that started on 31 July 2014 and ended on 1 August 2014. It showed up twice on the 1st and not at all on the 31st. (Calendar view)

**Comment by imposeren** [comment]
Events for last day of month do not work at all.  you can try my fork where this and several other issues are fixed:
https://github.com/imposeren/django-happenings/tree/django17

**Comment by wreckage** [comment]
This issue was fixed with this commit: 172ff22 and here's a test for it: efecd23. Thank you!
