### ISSUE TITLE
Locale is hardcoded to en_US.utf8 in utils/displays.py

### ISSUE THREAD

**Issue by BobBowles** [wreckage/django-happenings#8]
When I tried to run a test project, on the website I got 

    Error at /
    unsupported locale setting

The traceback shows the error is in /utils/displays.py, which uses a variable LOC hard-coded to `en_US.utf8`. This locale is not installed on my system.

Why can't this software use the default system locale, or (even better) the user's chosen session locale?

**Comment by BobBowles** [comment]
This works in Python 3.4 on Debian Wheezy:
utils/displays.py line 12:

    -- LOC = str(getattr(settings, "CALENDAR_LOCALE", "en_US.utf8"))
    ++LOC = str(getattr(settings, "CALENDAR_LOCALE", ""))

**Comment by wreckage** [comment]
Thanks! I tested out using the empty string on my machine and everything worked (in USA, using Arch Linux), and all tests pass on Travis, so I went ahead and updated the code. I also added a section to the readme called 'Locale' where I mention that the locale can be specified, if desired, using the CALENDAR_LOCALE setting in settings.py.

**Comment by BobBowles** [comment]
Thanks I will give it a spin tomorrow.
